from enum import Enum

class Document(Enum):
    RECAUDO_MULTAS = "/RECAUDO/MULTAS/"
    RECAUDO_DERECHOS_DE_TRANSITO = "/RECAUDO/DERECHOS DE TRANSITO/"
    CARTERA_MULTAS = "/CARTERA/MULTAS/"
    CARTERA_DERECHOS_DE_TRANSITO = "/CARTERA/DERECHOS DE TRANSITO/"

class WalletStatus(Enum):
    ACTIVE = "ACTIVO"
    INACTIVE = "INACTIVO"